[outputFormats]
[outputFormats.Offline]
baseName = "offline"
isHTML = true
notAlternative = true
mediaType = "text/html"

[[module.imports]]
path = "github.com/razonyang/hugopress"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-icons-bootstrap"

[[module.imports]]
path = "github.com/razonyang/hugo-mod-workbox"

[params.hugopress.modules.pwa.hooks.head-begin]
cacheable = true

[params.hugopress.modules.pwa.hooks.body-end]
weight = 1000

[params.pwa]
debug = false
icon_path = "images/pwa/icon.png"
icon_sizes = [48, 64, 128, 144, 256, 512]

# [[params.pwa.precaches]]
# url = ""

[params.pwa.caches.font]
strategy = "cache-first"
# 30d
max_age = 2592000

[params.pwa.caches.image]
strategy = "cache-first"
# 30d
max_age = 2592000

[params.pwa.caches.script]
strategy = "cache-first"
# 30d
max_age = 2592000

[params.pwa.caches.style]
strategy = "cache-first"
# 30d
max_age = 2592000
