baseURL = 'https://example.org'
languageCode = 'en-us'
title = 'Hugo PWA Example Site'

[[module.imports]]
path = "github.com/hugomods/pwa"

[outputs]
home = ["HTML", "RSS", "Offline", "WebAppManifest"]

[params]
description = "This PWA module for Hugo sites"

# Precache pages.
[[params.pwa.precaches]]
url = "/"
[[params.pwa.precaches]]
url = "/precached/"
